image: docker:19.03.1
services:
  - docker:19.03.1-dind

variables:
    BASE_TAG: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t ${BASE_TAG} .
    - docker push ${BASE_TAG}/${DISTRO}:${VER}


development:
  stage: deploy
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

stable:
  stage: deploy
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$(CI_BUILD_REF_NAME)" .
    - docker push "$CI_REGISTRY_IMAGE:$(CI_BUILD_REF_NAME)"
  only:
    - tags

