title: KiCad Docs
description: KiCad documentation
source: _source
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - src/
  - kicad-doc/
  - .docker/
  - '*.rb'
  - _templates
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - page-liquid
    - toc!

footer:
  forum_url: https://forum.kicad.info/
  github_url: https://github.com/kicad