= KiCad Docs Website Source


Docs website source for kicad :D


== Prerequisites


- Ruby 2.3 or higher
- Bundle


== Getting started

=== Ruby deps
After cloning the project, run

----
bundle install
----

to download the required ruby packages.

=== Kicad-doc source

----
git clone https://github.com/KiCad/kicad-doc.git kicad-doc
----

Build each required branch version as defined in _source/_data/versions.yml
Take the entire resulting /build/ folder (literally the entire folder) and rename it to the <VERSION> folder here

./kicad-doc-built/<VERSION>/


NOTE: This needs to be automated later for "local development"


=== Process the docs
The "build" folder docs then need to be transformed and wrestled into their final form for the site.

To do this just run

----
rake process_files
----


=== Running the site in development
Basic development can then be done by

----
jekyll serve
----

=== Running the complete site container
Local verification of the container for the pod can be tested by
building it, for exmaple with:

----
docker build -t kicadeda/kicad-docs-website .
----

And then it can be served locally by

----
docker run --rm -p 8081:8081 kicadeda/kicad-docs-website
----

To debug or inspect the stuff included in the image use

----
docker run --rm --entrypoint=ash -it kicadeda/kicad-docs-website
----
